server:
    #端口
    port: 8080
    session:
        #session过期期限
        timeout: 1000 # in seconds
    context-path: /dynamicDB
    
spring:
    application:
        name: dynamicDB
    #db  -- 默认数据源
    datasource:
    #jndi
#        type: javax.sql.DataSource
#        jndi-name: jdbc/frm 
    #mysql
        url: jdbc:mysql://127.0.0.1:3306/mc_test?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    #oracle      
#        url: jdbc:oracle:thin:@129.158.105.196:1521:xe
#        username: ORECOIN
#        password: Bcaus2018
#        type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
#        driver-class-name: oracle.jdbc.driver.OracleDriver
        
#mybatis                         
mybatis:
    mapper-locations: classpath:mapper/**/*Mapper.xml
    
# 更多数据源
custom:
    datasource:
        names: zqitDbTest,zqitDbTest2
        zqitDbTest:
#            type: javax.sql.DataSource
#            jndi-name: jdbc/frmA
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://121.201.97.113:3306/zqit_db_test?characterEncoding=UTF-8&useSSL=false
            username: root
            password: Zqit3503
        zqitDbTest2:
#            type: javax.sql.DataSource
#            jndi-name: jdbc/frmB
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://121.201.97.113:3306/zqit_db_test2?characterEncoding=UTF-8&useSSL=false
            username: root
            password: Zqit3503
            
#日志管理            
logging: 
    level: 
        zqit: 
            portal: debug

    
